kind: pipeline
type: docker
name: java-17

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: zot.nater0214.com
      repo: nater0214/java-with-ffmpeg
      tags:
        - "17"
      build_args:
        - JAVA_VERSION=17
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      pull_image: true
      no_cache: true

trigger:
  event:
    - push
    - cron
    - custom

---
kind: pipeline
type: docker
name: java-21

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: zot.nater0214.com
      repo: nater0214/java-with-ffmpeg
      tags:
        - "21"
        - "latest"
      build_args:
        - JAVA_VERSION=21
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      pull_image: true
      no_cache: true

trigger:
  event:
    - push
    - cron
    - custom

---
kind: pipeline
type: docker
name: java-25

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: zot.nater0214.com
      repo: nater0214/java-with-ffmpeg
      tags:
        - "25"
      build_args:
        - JAVA_VERSION=25
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      pull_image: true
      no_cache: true

trigger:
  event:
    - push
    - cron
    - custom